### ISSUE TITLE
Bug: Abyssinica-SIL "tswa alternate > Alternate" option fails with error

### ISSUE THREAD

**Issue by dyacob** [silnrsi/typetunerweb#2]
Selecting the Abyssinica SIL font on TypeTuner Web, the "Alternate" menu selection for the "tswa alternate" leads to the following error message:

```
Unexpected error from SIL Typetuner when processing font 'AbyssinicaSIL-Regular.ttf':

External program exited with return code 255
PostScript name uni133F.alt4 is not defined in the font. at typetuner.pl line 621.
Please click your browser's Back button, check your feature settings and try again.

Be aware that feature settings that require an input font will not work with TypeTuner Web
```

Looking into the font, I think `uni133F.oldstyle` may have been the intended glyph for this option.

**Comment by LornaSIL** [comment]
Thanks @dyacob. I think this is a bug in the TypeTuner code for Abyssinica. The code for TypeTuner is incorrect. Just to verify that it's working in other situations, I just tested the feature with a Graphite-enabled app and an Opentype-enabled app and it's working there. 

Can you tell me how urgent this is for you?

**Comment by dyacob** [comment]
Not urgent, I just wanted to bring it to the team's attention.

**Comment by LornaSIL** [comment]
@dyacob this bug has been fixed. That's the only change we made, so we won't make announcements.

**Comment by dyacob** [comment]
Thanks @LornaSIL , I noticed the update over the weekend and generated a new font from TypeTuner Web and it all looks good :-)
